packages/delphix-platform/config.sh
This is the corresponding `linux-pkg` change for https://github.com/delphix/delphix-platform/pull/24
=> Build multiple versions of the delphix-platform package

buildpkg.sh, lib/common.sh
Recent commit https://github.com/delphix/linux-pkg/commit/86f846f9669b77945b0582f8e9e51af1d7c9f6f5 broke auto-update. 
* build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/54
* update: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/update/7
* make check
=> Fix auto-update

package-lists/buildall.pkgs, package-lists/updateall.pkgs, packages/td-agent/config.sh, setup.sh
This adds our custom td-agent packaging with fluentd and all necessary plugins needed for our Insight module.
Corresponding change to include this custom td-agent package as part of `delphix-platform` is at -
https://github.com/delphix/delphix-platform/pull/51
Tests:
- Verified package build: `git-linux-pkg build -m pks-lx-bootstrap-new.dlpxdc.co td-agent`
- linux-pkg pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/70/  
- linux-pkg update: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/update/10/ 
- appliance-build-orchestrator : http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/506/console
- Created a VM …
=> LX-1645 Create custom td-agent package

package-lists/build/userland.pkgs, package-lists/update/userland.pkgs, packages/nfs-utils/config.sh
linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/287/console
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2054/console
linux-pkg-update: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/2/console
=> Add nfs-utils package

README.md, build-info-pkg/build-package.sh, lib/common.sh, packages/adoptopenjdk/config.sh, packages/challenge-response/config.sh, packages/connstat/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-platform/config.sh, packages/delphix-sso-app/config.sh, packages/java8/config.sh, packages/td-agent/config.sh
Backport of #60 to 6.0/release
=> [Backport to 6.0] Output debug symbol (.ddeb) packages

package-lists/build/userland.pkgs, packages/performance-diagnostics/config.sh
linux-pkg userland build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/release/job/userland/job/pre-push/7/console
@pzakha This should be all set to merge whenever it looks good to you.
=> Add performance-diagnostics package

package-lists/update/userland.pkgs
=> temporarily disable auto-update of crash package

.github/scripts/install-shellcheck.sh, .github/scripts/install-shfmt.sh, .github/workflows/main.yml
Add github actions to linux-pkg to perform checkstyle.
In the future we will add more sanity checks to linux-pkg PRs.
Made sure that the new actions pass on master
=> LB-256 Use github actions to perform sanity checks on pull-requests for linux-pkg

package-lists/build/userland.pkgs, packages/recovery-environment/config.sh
This PR adds support for the new recovery-environment project to be built into the Delphix engine automatically.
Tested with ab-pre-push and manual testing to verify that the recovery environment is successfully installed and configured. http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3375/console
=> Recov env package

package-lists/update/userland.pkgs
=> Stop updating "td-agent" due to build failure

README.md, buildpkg.sh, default-package-config.sh, packages/adoptopenjdk/config.sh, packages/delphix-sso-app/config.sh, packages/java8/config.sh
Issue Number: N/A
reviewed at https://github.com/delphix/linux-pkg/pull/109
-
-
-
=> Add check to verify copyright file exists for all platform packages.

README.md, buildpkg.sh, default-package-config.sh, packages/adoptopenjdk/config.sh, packages/delphix-sso-app/config.sh, packages/java8/config.sh, packages/td-agent-prebuilt/config.sh
Issue Number: N/A
Skip copyright check for td-agent-prebuilt package. - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/pre-push/89/
-
-
-
=> Add skip copyright check flag for td-agent prebuilt package

default-package-config.sh, packages/adoptopenjdk/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-sso-app/config.sh, packages/grub2/config.sh, packages/java8/config.sh
Issue Number: N/A
Update the script to check copyright from debian instead of repository -
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/pre-push/90/
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/kernel/job/pre-push/45/
-
-
-
=> update copyright check script

packages/adoptopenjdk/config.sh
=> Upgrade java to 8u262b10 (#115)

lib/common.sh
This now allows the auto-update logic to push changes to the remote using a git token. Previously only a combination of a user & password were supported.
GitHub is deprecating the usage of user:password auth for some of its APIs (https://developer.github.com/changes/2020-02-14-deprecating-password-auth/). It's unclear if `git push` is affected by this, but in any case using a token is a much better security practice.
Update Jenkins to pass a token instead of a user & password (see TOOL-10580).
Tested by running `./sync-with-upstream.sh bpftrace` manually on a bootstrap VM, targetting my developer fork of the `bpftrace` repo.
- Tested passing PUSH_GIT_TOKEN in env
- Tested passing PUSH_GIT_USER & PUSH_GIT_PASSWORD in env
- Tested not passing anything in env and getting prompted for a token
=> TOOL-10581 linux-pkg should be able to use git token to push to remote

README.md, lib/common.sh, setup.sh
=> [Backport of DLPX-73310 to 6.0.6.0] linux-pkg: enable building from release tag

default-package-config.sh, lib/common.sh, package-lists/update/main.pkgs
After this merge, we will start using our in-house kernels on 6.0/stage.
We should first integrate https://github.com/delphix/grub2/pull/13
- ab-pre-push (rebuilding all kernels & including grub changes in linked PR): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4783/
=> Merge master into 6.0/stage

packages/drgn/config.sh
dgrn repo has renamed "master" to "main"
=> change drgn upstream repo to main

packages/adoptopenjdk/config.sh
Upgrade JDK to latest available version
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6046/ - in progress
=> CP-5910 [Backport of CP-5633] Upgrade Engine JDK to version jdk8u302-b08

lib/common.sh
This is the linux-pkg part of the change that would allow our build system to build packages using private/internal github repositories.
Related devops-gate review: http://reviews.delphix.com/r/73005/
- Manually tested building the `https://github.com/delphix/delphix-rust` package while it was private
- Tested building packages using github & gitlab automation (more testing will be posted on the devops-gate review.
=> TOOL-12129 Allow fetching internal Delphix github repositories

lib/common.sh
=> TOOL-12170 [Backport of TOOL-12129 to 6.0.11.0] Allow fetching internal Delphix github repositories

lib/common.sh
Remove the test code that slipped into #194 
- Ran a quick sanity check manually to make sure build works
=> TOOL-12213 linux-pkg: run setup.sh automatically when needed (#194) (follow-on)

setup.sh
=> TOOL-12358 app-gate frontend build fails due to OOM

packages/challenge-response/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-sso-app/config.sh, packages/gdb-python/config.sh
Clean cherrypick of: https://www.github.com/delphix/linux-pkg/pull/201
=> GHM-188 [Backport of GHM-159 to 6.0/patch] Modify linux-pkg to point to GitHub version of repositories

packages/challenge-response/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-sso-app/config.sh, packages/gdb-python/config.sh
Clean cherrypick of: https://www.github.com/delphix/linux-pkg/pull/201
=> GHM-190 [Backport of GHM-159 to 6.0/stage] Modify linux-pkg to point to GitHub version of repositories

packages/challenge-response/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-sso-app/config.sh, packages/gdb-python/config.sh
Clean cherrypick of: https://www.github.com/delphix/linux-pkg/pull/201
=> GHM-189 [Backport of GHM-159 to 6.0/release] Modify linux-pkg to point to GitHub version of repositories
