lib/common.sh, package-lists/buildall.pkgs, package-lists/updateall.pkgs, packages/bpftrace/config.sh
This adds `bpftrace` package to the official linux-pkg package bundle.
It also adds `bpftrace` to the auto-update checker. I've also fixed broken logic in `update_upstream_from_git()`. Note that this function was only used by `bpftrace` so far since the other third-party packages use `update_upstream_from_source_package()` instead.
Note that this change doesn't add `bpftrace` to the appliance; for that bpftrace will need to be added as a dependency of `delphix-platform`.
**TESTING**
- build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/10/console
- update (no updates performed): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/update/5/console
- manually ran `updateall.sh` …
=> Add bpftrace to buildall and updateall

packages/make-jpkg/config.sh
This adds a package definition for `make-jpkg`.
Note that with this change this package will not be built or updated automatically.
- Ran `make check`
- Build with `./buildpkg.sh make-jpkg` and installed produced package on a `bootstrap-18-04` system:
```
$ apt show java-package
Package: java-package
Version: 0.63-delphix-2019.01.16.19
Status: install ok installed
Priority: optional
Section: contrib/misc
Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Installed-Size: 71.7 kB
Depends: debhelper (>= 11), build-essential, dpkg-dev, fakeroot, libasound2, libfontconfig1, libgl1-mesa-glx, libgtk2.0-0, libx11-6, libxslt1.1, libxtst6, libxxf86vm1, unzip
Suggests: openjdk-8-jre
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status …
```
=> Add package definition for make-jpkg

package-lists/buildall.pkgs, package-lists/updateall.pkgs, packages/bcc/config.sh, packages/bpftrace/config.sh
This adds bcc to linux-pkg.
This depends on https://github.com/delphix/bcc/pull/1 and https://github.com/delphix/delphix-platform/pull/40
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/27/
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/417/ (Failed due to conflict with libbpfcc)
Added dependency on https://github.com/delphix/delphix-platform/pull/40:
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/30/
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/419/ (Pass, except for DLPX-62465)
=> Add bcc and have bpftrace depend on it

updateall.sh
We keep seeing "Nothing to report" in slack for the update job.
This is getting rid of it.
**TESTING**
- make check
- update job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/update/6/console
=> Remove the "Nothing to report" report

lib/common.sh, packages/bcc/config.sh, packages/bpftrace/config.sh
Without this, we can only specify branches or tags when fetching the source for building a package.
With this, we can specify references like `refs/heads/master`.
This work is needed for `git-ab-pre-push` to work with repositories managed by linux-pkg.
* linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/50
* linux-pkg-build with ref passed as branch: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/51
* make check
=> Allow fetching refs for package repositories

lib/common.sh, packages/ptools/config.sh
We want to stop coloring the output of `dpkg-buildpackage` when ran from Jenkins as it causes coloring issues when building certain packages (e.g. `bcc`). Another side-effect of coloring issues is that invisible characters can get copied along when copying Jenkins console strings.
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/69
- make check
=> Coloring in dpkg-buildpackage is broken when output in Jenkins

lib/common.sh, packages/adoptopenjdk/config.sh
Since we've seen a few issues when fetching packages from external repositories (e.g. #7), this should hopefully help us in case there are intermittent issues.
- linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/96/
- make check
- negative test installing broken dependencies: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/117/console
=>  Retry multiple times when installing package dependencies

package-lists/buildall.pkgs, packages/java8/config.sh
Add Java 8 package to Linux-pkg.
The main goal here is to stop building Java in appliance-build and do it in Linux-pkg instead. This is also a prerequisite for adding the SSO app to Linux-pkg.
Remove Java build from appliance-build
* linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/144/
* ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/651/
* make check
* Tested manually building with the SSO app
=> add Java 8

package-lists/buildall.pkgs, packages/delphix-sso-app/config.sh
Automated Tests: 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/pre-push/173/consoleFull
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/687/console
Tested manually by runing:
`./buildpkg.sh delphix-sso-app` with java 8 package installed and without it installed, and the java 8 package was installed as well as the delphix-sso-app.
=> Add SSO-App project

package-lists/build/userland.pkgs
This change is part of the PHASE 2 of the linux-pkg build list project here (Step 15):
https://jira.delphix.com/browse/TOOL-7378
Here is a spreadsheet that shows the dependencies for this commit:
https://docs.google.com/spreadsheets/d/1-qRT4esBl0827wKCpsNe8veXJnH2s8k1fWr20me260Q
Since we are now using the kernel package list in appliance-build, we no longer want to build kernel packages as part of the userland package list.
1. Build userland and kernel package lists:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/1/
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/2/
2. Use the build artifacts to generate a new appliance (Note that testing …
=> TOOL-7381 linux-pkg userland build list should not build kernel modules

package-lists/build/userland.pkgs, packages/adoptopenjdk/config.sh, packages/delphix-sso-app/config.sh
AdoptopenJDK is added to the userland build list for virtualization and masking.
once changes for Virtualization and Masking are pushed, `java8` can safely be removed from the list.
**Testing:**
added adoptopenjdk-java8 as dependency in app-gate instead of oracle-java8 -> ran pre-push -> http://selfservice.jenkins.delphix.com/job/dlpx-app-gate/job/master/job/build-package/job/pre-push/412/
pre-push for linux-pkg with adoptopenjdk changes -> http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/8/
appliance-build-orchestrator-pre-push with S3 links from above runs -> http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/766/
=>  Add adoptopenjdk to userland list

packages/bpftrace/config.sh
Upstream has added a new build dependency on `systemtap-sdt-dev`.
This causes build failures on an attempt to merge with upstream.
- linux-pkg-build with bpftrace merged with upstream:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/27/console
- make check
=> add bpftrace build dependency systemtap-sdt-dev

packages/td-agent/config.sh
Upstream `td-agent` package version was updated to 3.4.0 and I've fixed our custom td-agent package's upstream merge via - https://github.com/delphix/omnibus-td-agent/pull/2
This PR is to update the corresponding base version in `td-agent` package build to 3.4.0
=> Update default td-agent package base version to 3.4.0

packages/adoptopenjdk/config.sh
Related Reviews:
app-gate: http://reviews.delphix.com/r/50102/
masking: http://reviews.delphix.com/r/50104/
linux pre-push - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/138/
appliance-build-orchestrator-pre-push -  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1362/
Verification on image from ab-pre-push:
```delphix@ip-10-110-253-34:~$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
delphix@ip-10-110-253-34:~$ javac -version
javac 1.8.0_212
```
=> upgrade java to 8u212

packages/zfs/config.sh
This will allow us to require `zfs-precommit` and `git-ab-pre-push` to run checkstyle on ZFS changes later on. Right now, this can be ran manually by setting checking `CHECKSTYLE` in the Jenkins build job (See job in testing section), or by running `./buildpkg -c zfs` in `linux-pkg`.
- http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/2/
- make check
=> Add checkstyle hook for ZFS

packages/td-agent/config.sh
Upstream `td-agent` package version was updated to 3.4.1 and I've updated our down stream `td-agent` plugins to match that via - https://github.com/delphix/omnibus-td-agent/pull/4
So, this PR just updates our corresponding `td-agent` package version to 3.4.1 to reflect the same.
=> Update current version to 3.4.1

README.md, buildpkg.sh, default-package-config.sh, packages/adoptopenjdk/config.sh, packages/bcc/config.sh, packages/bpftrace/config.sh, packages/challenge-response/config.sh, packages/cloud-init/config.sh, packages/connstat/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-kernel/config.sh, packages/delphix-platform/config.sh, packages/drgn/config.sh, packages/gdb-python/config.sh, packages/java8/config.sh, packages/libkdumpfile/config.sh, packages/make-jpkg/config.sh, packages/python-rtslib-fb/config.sh, packages/targetcli-fb/config.sh, packages/td-agent/config.sh, packages/zfs/config.sh, template/config.sh
With this code in place, we can simplify the `config.sh` file for most packages by removing the call to `store_git_info()`. This will also make sure that whenever we build a package from git, the build info is always stored as we forgot to add it for a few packages.
- make check
- verify contents of new global build-info file
- linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/261/
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1792
=> Store Build Info by default

package-lists/build/userland.pkgs, packages/libkdumpfile/config.sh
We've integrated changes to "drgn" such that it will automatically
detect "libkdumpfile" if it's installed, and enable support for kernel
core dump files when it's detected. To ensure "drgn" is built with this
functionality enabled, we need to install the "libkdumpfile" package
after building it, and prior to building the "drgn" package.
=> Use "libkdumpfile" when building "drgn"

package-lists/build/userland.pkgs, packages/makedumpfile/config.sh
**Description**
Add `makedumpfile` package
We need a modified `makedumpfile(8)` command that can filter ZFS file data pages from the kernel crash dump file. This package is one part of the necessary changes to bring about ZFS file data page filtering.
**Related Changes**
The makedumpfile patch is at https://github.com/delphix/makedumpfile/commit/9d7983e44b which adds the `'--private-page-filter'` option
A corresponding ZFS kernel module changes landed in: 
https://github.com/zfsonlinux/zfs/commit/28c91ab66d
A follow up change, once this patch has landed, is to change the /etc/default/kdump-tools configuration file to start passing the `--private-page-filter` option to makedumpfile.
**Testing**
Appliance build pre-push (using linux-pkg userland build artifacts): …
=> DLPX-64156 crashdump should only include ZFS metadata

packages/libkdumpfile/config.sh, packages/makedumpfile/config.sh
We should build packages according to the DEFAULT_BRANCH branch
which is passed by Jenkins and is the same for linux-pkg and all
its packages.
If we branch out to `6.0/stage`, then we'd have to manually update `DEFAULT_PACKAGE_GIT_BRANCH` to `6.0/stage`. Instead of doing that, we should just leave `DEFAULT_PACKAGE_GIT_BRANCH` unset.
- linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/307/
=> Do not set DEFAULT_PACKAGE_GIT_BRANCH to master

packages/bpftrace/config.sh
Following the changes in https://github.com/delphix/bpftrace/pull/3, we no longer need a custom PPA for clang and llvm to build bpftrace.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2183/
=> Custom PPA no longer needed to build bpftrace

package-lists/build/td-agent.pkgs, package-lists/build/userland.pkgs, packages/td-agent-prebuilt/config.sh
Do not re-build td-agent on every userland packages build.
The main issue with the td-agent is that it consumes a lot of external dependencies on which we do not have control. While some of those dependencies could be mirrored, for others it's quite complex. Because of a recent breakage in td-agent's dependencies, where a package was pulled from the Ruby Gems public repository, td-agent cannot be currently built. Until we figure either how to make td-agent's build more reliable or not have failures affect the rest of the build, we will be using a pre-built td-agent package deployed into artifactory.
This is a temporary change to unblock the build, we may iterate on it further in the upcoming days/weeks.
- linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/jo …
=> Use a pre-built package for td-agent

packages/drgn/config.sh
Recently drgn started builting the latest elfutils as part of its
building process. Ensure that the prerequisites for that library
are installed on the system before attempting to build drgn.
For reference the commits that caused this are the following:
1cedca8ff4e39207aa5b0a1a34793dcbdb1f025f
6a13d74c0c45881c7e26b3c16a2d76413c740641
Side-note:
From my discussion with Pavel, it seems like it would be better
to add all the dependencies of the debian config in the `drgn`
repo and change the `prepare()` function in `linux-pkg` to do
`install_build_deps_from_control_file()`. This way we don't have
to change `linux-pkg` every time some dependency changes in
`drgn` (plus it would make our repo more self-contained for
folks outside Delphix who want to create a debian package out
of it). The …
=> Fix drgn build failures caused by building elfutil from scratch

branch.config, buildlist.sh, lib/common.sh, setup.sh
Update linux-pkg-build setup to add the internal linux package mirror as an apt source before doing the build.
Testing:
Ran linux-pkg-build kernel 
http://collins.d.delphix.com:35379/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/post-push/26/
Ran linux-pkg-build userland
http://collins.d.delphix.com:35379/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/post-push/1/
With the output from the above, I ran ab-pre-push 
http://collins.d.delphix.com:35379/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/47/parameters/
and cloned the resulting VM and compared installed packages to a current trunk VM via `dpkg-query -l`, I noted that the only differences were build versions that contain dates of some packages, as my build …
=> LB-215 Want linux-pkg-build to use package mirror

README.md, build-info-pkg/build-package.sh, lib/common.sh, packages/adoptopenjdk/config.sh, packages/challenge-response/config.sh, packages/connstat/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-platform/config.sh, packages/delphix-sso-app/config.sh, packages/java8/config.sh, packages/td-agent/config.sh
linux-pkg already creates `.ddeb` packages where appropriate, we just need to copy them to the `artifacts/` directory so that they get uploaded with the rest of the packages by Jenkins at the end of a build.
This mostly just involves changing `mv ./*.debs ...` to `mv ./*debs ...` so that the glob will match `.ddeb` packages as well. Note that I've made this change in a few places where it isn't strictly necessary (in packages that don't produce a corresponding `ddeb` package), because it doesn't hurt anything and it helps to establish a pattern to be followed in the future.
=> Output debug symbol (.ddeb) packages

packages/drgn/config.sh
depends on: https://github.com/delphix/drgn/pull/3
Testing:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/356/
userland-job without the pkg-changes:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/357/
=> drgn: install build dependencies using info from control file

package-lists/build/userland.pkgs, packages/performance-diagnostics/config.sh
Create performance-diagnostics package and add it to `userland` list. Note that this shouldn't be merged until `DEFAULT_PACKAGE_GIT_URL` has been updated, which can be done after the performance-diagnostics code is pushed to the official repo.
=> Add performance-diagnostics package

packages/drgn/config.sh
linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/release/job/userland/job/pre-push/11/
=> [Backport to 6.0.0.0] drgn: install build dependencies using info from control file

README.md, lib/common.sh, setup.sh
This is part 2 of 2 for DLPX-67499.
Part 1 of 2 is here: https://github.com/delphix/delphix-kernel/pull/8
We change the logic to determine the latest kernel version for the "generic" kernel flavour to look at the package `linux-generic-hwe-18.04` instead of `linux-image-generic`.
As an additional change, we add a new variable for the Ubuntu distribution we are building for. This will make it easier for us to switch to a new Ubuntu distribution later.
Both parts of this change must be pushed at the same time, otherwise appliance-build will be broken.
linux-pkg-build [kernel]: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/113/
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance …
=> DLPX-67499 Use the HWE kernel for the generic platform on Ubuntu 18.04 (Part 2 of 2)

README.md, lib/common.sh, setup.sh
Clean backport of: https://github.com/delphix/linux-pkg/pull/69
Co-dependent change: https://github.com/delphix/delphix-kernel/pull/9
See https://github.com/delphix/delphix-kernel/pull/9
=> DLPX-67514 [Backport of Issue DLPX-67499 to 6.0.0.0] Use the HWE kernel for the generic platform on Ubuntu 18.04

package-lists/build/userland.pkgs, package-lists/update/userland.pkgs, packages/crash/config.sh
See PR: https://github.com/delphix/crash/pull/1
Testing on latest 5.0:
```
delphix@ip-10-110-241-113:~$ sudo crash /usr/lib/debug/boot/vmlinux-4.15.0-1056-aws
crash 7.2.7++
Copyright (C) 2002-2019  Red Hat, Inc.
Copyright (C) 2004, 2005, 2006, 2010  IBM Corporation
Copyright (C) 1999-2006  Hewlett-Packard Co
Copyright (C) 2005, 2006, 2011, 2012  Fujitsu Limited
Copyright (C) 2006, 2007  VA Linux Systems Japan K.K.
Copyright (C) 2005, 2011  NEC Corporation
Copyright (C) 1999, 2002, 2007  Silicon Graphics, Inc.
Copyright (C) 1999, 2000, 2001, 2002  Mission Critical Linux, Inc.
This program is free software, covered by the GNU General Public License,
and you are welcome to change it and/or distribute copies of it under
certain conditions.  Enter "help copying" to see the conditions.
This …
```
=> add latest crash-util

package-lists/update/userland.pkgs
This reverts commit e9e5a3802342f83fd8f4b34f1c52506daa80c471.
Re-enable auto-update of the crash package, now that the appropriate changes were done to the `delphix/crash` repository.
linux-pkg update job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/4/consoleFull
=> Revert "temporarily disable auto-update of crash package"

lib/common.sh
This change introduces an oracle-specific kernel and remove the kvm-specific kernel which is no longer used. The kvm-specific kernel is no longer used by any of our platforms and the kvm platform now relies on the generic kernel (see https://github.com/delphix/delphix-platform/pull/151)
=> DLPX-67915 Add oracle-specific kernel

package-lists/update/userland.pkgs, packages/makedumpfile/config.sh
Enable auto-update for the makedumpfile package and do not
remove kdump-tools to keep both packages built from the same source.
Also prepended `1:` to version numbering to match Ubuntu's versioning schema (note that without this, the build is broken as `kexec-tools` has `Breaks: kdump-tools (<< 1:1.5.9-6)`)
- ab-pre-push (linux-pkg only): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2886/
- ab-pre-push (including merging latest makedumpfile): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2877/
- Tested auto-update works properly with `./updatelist -n …
=> DLPX-68435 crash dump fails on 5.3 kernel

README.md, packages/crash-python/config.sh, packages/gdb-python/config.sh
Given our versioning model, where each package managed by linux-pkg
is tagged and branched according to releases, we should rely on the
DEFAULT_BRANCH parameter for fetching the source code for each package.
Setting DEFAULT_PACKAGE_GIT_BRANCH is dangerous for 2 reasons:
- First because a release tag for that repository then becomes
misleading, as it is not what is used to rebuild that repository
for a particular release version.
- Second, if changes are later pushed to that branch, then rebuilding
the original release will pull those new changes.
For now, DEFAULT_PACKAGE_GIT_BRANCH is being deprecated rather than
removed. We will evaluate whether it still has value for testing
purposes or for projects such as SUV.
- Update `master` branch for `crash-python` to point to current `next` …
=> Deprecating DEFAULT_PACKAGE_GIT_BRANCH

README.md, packages/crash-python/config.sh, packages/gdb-python/config.sh
Clean cherry-pick of https://github.com/delphix/linux-pkg/pull/80
linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/pre-push/16/
=> [Backport to 6.0.1.0] Deprecating DEFAULT_PACKAGE_GIT_BRANCH

README.md, packages/crash-python/config.sh, packages/gdb-python/config.sh
Clean cherry-pick of #80
linux-pkg-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/patch/job/userland/job/pre-push/1/
=> [Backport to 6.0.0.1] Deprecating DEFAULT_PACKAGE_GIT_BRANCH

package-lists/update/userland.pkgs, packages/libkdumpfile/config.sh
Relevant libkdumpfile PR: https://github.com/delphix/libkdumpfile/pull/1
Created userland pkg-build job setting the following:
```
LINUX_PKG_GIT_URL: https://github.com/sdimitro/linux-pkg.git
LINUX_PKG_GIT_BRANCH: libkdumpfile_sync
SINGLE_PACKAGE_GIT_URL: https://github.com/sdimitro/libkdumpfile.git
SINGLE_PACKAGE_GIT_BRANCH: debian_dir
```
URL: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/527/
=> libkdumpfile: abstract out dependencies and sync with upstream

package-lists/update/userland.pkgs, packages/libkdumpfile/config.sh
userland pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/555/
Used the S3 link from the above and run the following ab-pre-push:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3167/
Even though the above is still pending a new image was created for ESX where I was able to ensure that the new libkdumpfile bits are there and usable for kdumps by `sdb` and `drgn`.
=> Backport: libkdumpfile: abstract out dependencies and sync with upstream

package-lists/build/userland.pkgs, packages/walinuxagent/config.sh
Testing:
Userland build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/569/console
Kernel build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/153/console
Appliance build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3244/console
=> DLPX-69161 [Backport of DLPX-69137 6.0.2.0] walinuxagent package needs to be updated

package-lists/build/kernel.pkgs, package-lists/update/userland.pkgs, packages/grub2/config.sh, packages/zfs/config.sh
This patch adds the grub2 package to the build process. This package recently had its own official repo added to the Delphix organization, and the patches to enable the recovery environment work there are still under review.
Tested via manual builds and installation of the produced packages, and also via automation:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/568/ and http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/150/ .  Note that the latter build failed; this is because our version of grub2 doesn't yet have the patch that fixes the build to work on ubuntu with a custom version of ZFS installed. I will update with a new run when that …
=> Add grub2 package to the Delphix build process

.github/scripts/verify-query-packages.sh, .github/workflows/main.yml, buildpkg.sh, lib/common.sh, query-packages.sh, setup.sh
See Jira for more context.
- The `determine_default_git_branch()` function is now called explicitly to avoid having code run when including the lib/common.sh file (especially code that produces output).
- Added new github action to sanity test the query-packages command.
linux-pkg-build kernel: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/kernel/job/pre-push/165/
linux-pkg-build userland: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/572/
linux-pkg-update: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/6/
```
~/linux-pkg$ …
```
=> LB-290 Add query-packages script to linux-pkg

package-lists/build/kernel.pkgs, packages/linux-prebuilt/config.sh
This change specifically targets 6.0.2.1. Three kernel packages were
manually rebuilt, and their revision number was bumped. Those packages
will be used by appliance-build instead of the Ubuntu kernel packages
with the same name.
Note that the `linux-prebuilt` package is only a temporary measure to have those packages included in 6.0.2.1. We will likely need a similar patch in 6.0.3.0. For later releases we will most likely not need this because:
1. The automation for building our own kernel image packages should be completed.
2. The fix should be upstreamed and pulled by Ubuntu.
6.0.2.1 has the following kernel packages:
- 4.15.0-1031-oracle
- 4.15.0-1057-aws
- 5.0.0-1028-azure
- 5.0.0-1028-gcp
- 5.0.0-37-generic
The 4.15 kernel is not affected by this issue, hence we only provide custom …
=> DLPX-69902 [Backport of DLPX-69864 to 6.0.2.1] iSCSI LUN reset command leaks reference and prevents LUN from being deleted

.github/scripts/install-shellcheck.sh, .github/scripts/install-shfmt.sh, .github/scripts/verify-query-packages.sh, .github/workflows/main.yml, buildpkg.sh, lib/common.sh, query-packages.sh, setup.sh
Clean cherry-picks of:
- LB-256 Use github actions to perform sanity checks on pull-requests for linux-pkg
- LB-290 Add query-packages script to linux-pkg (#89)
- run `.github/scripts/verify-query-packages.sh`
- linux-pkg-build userland: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/pre-push/63
=> [Backport to 6.0.3.0] Fixes for LB-256 and LB-290

package-lists/build/kernel.pkgs, packages/linux-prebuilt/config.sh
Kernel packages with fixes for DLPX-70275 and DLPX-70278 were build
manually and stored in artifactory.
Here are the actual code fixes generic kernel: https://github.com/pzakha/linux/commits/dlpx-70276-generic
Note that the same changes have been cherry-picked cleanly on the other 4 kernels: aws, azure, gcp, oracle.
For details on the actual kernel fixes, see JIRA:
- DLPX-69953 (main bug for DLPX-70275)
- DLPX-69864 (main bug for DLPX-70278)
- ab-pre-push for esx: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3588/
- ab-pre-push for aws: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3587/
- ab-pre-push for azure, gcp, oci (build only, no tests): …
=> DLPX-70277 [Backport of DLPX-70276 to 6.0.3.0] Use a pre-built linux kernel in linux-pkg

packages/libkdumpfile/config.sh
Recently libkdumpfile changed its main branch name from
`master` to `tip`. Update the branch definition in our
repo to reflect this change.
(before the change) http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/449/
(with change)
userland-update job: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/450/
=> Upstream libkdumpfile branch name update

packages/libkdumpfile/config.sh
Recently libkdumpfile changed its main branch name from
`master` to `tip`. Update the branch definition in our
repo to reflect this change.
Testing:
update job dry-run:
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/451/
libkdumpfile was successful on the above run but td-agent failed with the following error:
```
19:34:00  To https://github.com/delphix/omnibus-td-agent.git
19:34:00   ! [rejected]        repo-HEAD -> master (fetch first)
19:34:00  error: failed to push some refs to 'https://****:****@github.com/delphix/omnibus-td-agent.git'
19:34:00  hint: Updates were rejected because the remote contains work that you do
19:34:00  hint: not have locally. This is usually caused by another repository pushing
19:34:00  hint: …
```
=> backport: Upstream libkdumpfile branch name update

package-lists/build/kernel.pkgs, package-lists/build/userland.pkgs, packages/recovery-environment/config.sh
This PR moves the recovery-environment package into the kernel build chain so that it can take the zfs build products to install them into the recovery environment.  This PR is intended to merged in conjunction with https://github.com/delphix/recovery-environment/pull/3.  It has been tested by running ab-pre-push , and by loading the built recovery environment onto a test VM and verifying that the system can import pools while in the recovery environment.
=> Route zfs package into recovery environment build

lib/common.sh, setup.sh
The 5.4 kernel headers define CONFIG_CC_HAS_ASM_INLINE, which prevents
kernel modules from being compiled with gcc 7. This is
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849348
Issue Number: TOOL-9951
The linux-package-mirror-sync job stopped working due to the above mentioned bug. Package creation
for kernel modules would fail.
With the new compiler, kernel module compilation works again.
linux-package-mirror-sync test using this change:
http://collins.d.delphix.com:24041/job/devops-gate/job/master/job/linux-package-mirror-sync/job/master/job/mirror2-sync/7/consoleFull
linux-pkg-build jobs for kernel and userland …
=> Use gcc 8 for linux-pkg

package-lists/build/kernel.pkgs, package-lists/build/userland.pkgs, package-lists/update/userland.pkgs, packages/grub2/config.sh, packages/recovery-environment/config.sh, packages/zfs/config.sh
This is a nearly-clean backport of the change to the linux-pkg repository that adds grub2 to the linux-pkg build process.  The grub package builds successfully on my test VM.
=> Backport: Add grub and recovery environment commits to linux-pkg

default-package-config.sh, packages/linux-kernel-aws/config.sh, packages/linux-kernel-azure/config.sh, packages/linux-kernel-gcp/config.sh, packages/linux-kernel-generic/config.sh, packages/linux-kernel-oracle/config.sh
Build and update kernel variants through linux-pkg
= Motivation
The Ubuntu kernels have served us well but we currently have two
problems with them:
1] When we trigger a kernel bug we have to wait until a patch is
released by Canonical. This may sound like a rare event but
we've already hit bugs in iSCSI and NFS subsystems that we've
had to work around.
2] There are certain kernel config options that we'd like to enable
that won't be enabled by Canonical until later releases or at
all even. Examples include BTF info in vmlinux and the PSI api
needed by oomd.
= This Patch
Enable linux-pkg to compile the Ubuntu kernels from scratch. In
addition it allows us to base our own patches on top of these
kernels, and rebase them whenever we get new commits from the
upstream Canonical kernels. This …
=> Build and update kernel variants through linux-pkg

packages/adoptopenjdk/config.sh
This change updates the JDK version to 8u262b10.
Related reviews:
app-gate: http://reviews.delphix.com/r/60913/
masking: http://reviews.delphix.com/r/60914/
linux pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/631
appliance-build-orchestrator-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3888/
Verification on image from ab-pre-push:
```
delphix@ip-10-110-215-233:~$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b10, mixed mode)
```
=> Upgrade java to 8u262b10

lib/common.sh, setup.sh
The 5.4 kernel headers define CONFIG_CC_HAS_ASM_INLINE, which prevents
kernel modules from being compiled with gcc 7.
Clean cherry-pick. This work is required for bumping our kernel in 6.0.5.0.
- linux-pkg-build userland: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/pre-push/92/
- linux-pkg-build kernel: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/kernel/job/pre-push/49/
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3943/
=> [Backport to 6.0.5.0] Use gcc 8 for linux-pkg (#107)

package-lists/build/userland.pkgs, packages/savedump/config.sh
Relevant change in Delphix platform: https://github.com/delphix/delphix-platform/pull/246
linux-pkg userland job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/637/
appliance-build job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3947/
manual testing on VM group created by appliance-build job above:
```
delphix@ip-10-110-232-241:~$ savedump -h
usage: savedump [-h] dump
Archive Linux crash dumps
positional arguments:
dump        the dump to be archived
optional arguments:
-h, --help  show this help message and exit
```
=> Add savedump userland package

package-lists/build/userland.pkgs, package-lists/update/userland.pkgs, packages/crash/config.sh, packages/savedump/config.sh
Clean cherry-picks of 375bc36cc3aad40e13e4f79467f17ef119d75d7b and fcb13c94014273ee94596591381702944c9dda3e
Using change in delphix-platform 6.0/stage -> https://github.com/delphix/delphix-platform/pull/247
linux-pkg userland job: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/643/
ab-pre-push with s3 link from above: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3987/flowGraphTable/
manual testing in provisioned VM:
```
delphix@ip-10-110-253-150:~$ ls -l /usr/bin/crash
-rwxr-xr-x 1 root root 8364632 Sep  9 23:25 /usr/bin/crash
delphix@ip-10-110-253-150:~$ ls -l /usr/bin/savedump
-rwxr-xr-x 1 root root 387 Sep  9 23:45 /usr/bin/savedump
```
=> savedump and crash-util for 6.0/stage

packages/linux-prebuilt/config.sh
I've rebuilt the latest linux kernel modules packages for 6.0/stage with our iSCSI fixes for DLPX-69953.
I've used the same procedure as for https://github.com/delphix/linux-pkg/pull/96. See https://github.com/pzakha/linux/tree/6050-generic for an overview of the changes. Changes for other platforms are published to branches `6050-<flavour>`. Note that DLPX-69864 has already been integrated upstream so you will not see a Delphix commit for it.
@grodr has synced the 6.0/stage linux package mirror (http://linux-package-mirror.delphix.com/6.0/stage/0fb27f0b/) without updating the "latest" 6.0/stage url. I've first used that mirror link to discover the latest versions of the kernel, then later in my testing.
Latest kernel versions are:
- 5.4.0-42-generic
- 5.3.0-1033-aws
- 5.3.0-1035-azure
- …
=> DLPX-71696 [Backport of DLPX-71695 to 6.0.5.0] Update kernel for 6.0.5.0

lib/common.sh
This is related to https://github.com/delphix/delphix-kernel/pull/16.
In terms of impact, this change is very similar to https://github.com/delphix/linux-pkg/pull/125, i.e. the build will likely keep working without this change but we would want to have it for the sake of completeness / correctness.
build-kernel: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-kernel/job/pre-push/8/console
=> Download linux-cloud-tools package when fetching kernel packages

lib/common.sh
The idea for the linux-pkg's linux-kernel-* packages, is that we will store in S3 all of the linux-kernel packages required to build the Delphix Appliance, without relying on the linux-package-mirror snapshot that is passed to appliance-build to contain them.
Some linux-kernel packages have dependencies on other linux-kernel packages. It seems that in some cases the dbgsym package has dependencies on another dbgsym package with a slightly different naming convention, and we were not downloading it.
Here's an example:
`linux-image-5.4.0-48-generic-dbgsym` depends on `linux-image-unsigned-5.4.0-48-generic-dbgsym`.
Note that we've already had some logic to deal with a similar issue that we had with the "tools" and "headers" packages, so this just extends the same logic to the dbgsym package. …
=> Fetch dependency of linux dbgsym package when downloading kernel packages

README.md, lib/common.sh, setup.sh
When using a release tag in DEFAULT_GIT_BRANCH the linux-package-mirror
link and the base url for fetching build dependencies are now properly
set up.
- ab-pre-push (rebuilding zfs + dependenciees & targetcli-fb): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4395
- manually tested that the logic works on bootstrap VM. Note that given that we do not currently have a release which uses "combined-packages" artifacts, I had to provide a custom `DEPENDENCIES_BASE_URL` link to make it work; that said I verified that the logic from `determine_dependencies_base_url()` should be compatible with artifacts that will be generated for 6.0.6.0 and later.
=> DLPX-73310 linux-pkg: enable building from release tag

default-package-config.sh
In the auto-update logic for the linux kernel, we rely on Ubuntu to tag their new kernel releases using a certain tag format. That format has changed for HWE kernels. It used to be:
```
Ubuntu-hwe-5.3.0-69.65 
```
Now it is:
```
Ubuntu-hwe-5.4-5.4.0-31.35_18.04.2 
```
Notice the "5.4" prefixing the kernel version.
This is now the same format that Ubuntu is using for other kernel flavours.
Before: http://collins.d.delphix.com:21968/job/devops-gate/job/master/job/linux-pkg/job/master/job/update-package/job/linux-kernel-generic/1/
With this fix: http://collins.d.delphix.com:21968/job/devops-gate/job/master/job/linux-pkg/job/master/job/update-package/job/linux-kernel-generic/2/
=> DLPX-73657 linux-pkg auto-update: git tags for hwe kernel now has the same format as other kernel flavours

default-package-config.sh
There are 3 distinct changes here:
When the Ubuntu kernel is built, it also pulls some 3rd party kernel modules out-of-tree, compiles them separately and packages them along with the kernel package. Not only do we not need those 3rd party kernel modules in our kernel, but they also introduce additional 3rd party dependencies to our build process. Recently, when trying to build the latest kernel one of those dependencies, nvidia, could not be located on the Ubuntu servers and so would cause the build to fail:
```
18:43:28  II: dkms-build downloading nvidia-390 (nvidia-kernel-source-390_390.141-0ubuntu0~0.20.04.1_amd64.deb)
18:43:28  II: fetching https://launchpad.net/ubuntu/+archive/primary/+files/nvidia-kernel-source-390_390.141-0ubuntu0~0.20.04.1_amd64.deb
18:43:29  curl: (22) The …
```
=> DLPX-73763 Fix kernel build and auto-sync logic

lib/common.sh, package-lists/update/main.pkgs
This enables the usage of our in-house linux kernel.
- Build packages & test on aws: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/685/
- Build appliance for esx, aws, gcp, oci, azure: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/686
- Test upgrade on aws: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/upgrade-testing/4368/
=> DLPX-73791 Use linux kernel packages built in-house

package-lists/build/main.pkgs
Adding `docker-python-image` to main.pkgs after the package's job is generated.
After the job was generated the first run was successful:
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/docker-python-image/job/post-push/1/
Also ran combine-packages job to verify everything gets put together properly: 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/combine-packages/job/pre-push/299/console
In the COMPONENTS artifacts (http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/combine-packages/job/pre-push/299/artifact/COMPONENTS/*view*/) an entry for the new package exists:
docker-python-image: …
=> CP-4543 main.pkgs update follow on

package-lists/build/main.pkgs
`build-packages` is [here](http://collins.d.delphix.com:29627/job/devops-gate/job/master/job/linux-pkg/job/6.0/job/stage/job/build-packages/job/post-push/8/)
`build-package` is [here](http://collins.d.delphix.com:29627/job/devops-gate/job/master/job/linux-pkg/job/6.0/job/stage/job/build-package/job/masking/job/post-push/1/)
=> TOOL-11187 leverage linux-pkg to build delphix-masking package (#141)

packages/virtualization/config.sh
This change adds virtualenv to the build dependencies when the virtualization package is being built. This is needed so that some pip and python commands can be run to generate files for the plugin runtime project.
Confirmed from a run that linked linux-pkg that this was built properly and virtualenv was used to install something via gradle during the build.
This diff is needed for http://reviews.delphix.com/r/67972/ to be pushed.
=> CP-4898 Write gradle task to download grpcio and generate grpc files

README.md, buildpkg.sh, lib/common.sh, packages/bpftrace/config.sh, packages/challenge-response/config.sh, packages/cloud-init/config.sh, packages/connstat/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-kernel/config.sh, packages/delphix-platform/config.sh, packages/docker-python-image/config.sh, packages/drgn/config.sh, packages/gdb-python/config.sh, packages/grub2/config.sh, packages/libkdumpfile/config.sh, packages/make-jpkg/config.sh, packages/makedumpfile/config.sh, packages/nfs-utils/config.sh, packages/performance-diagnostics/config.sh, packages/python-rtslib-fb/config.sh, packages/recovery-environment/config.sh, packages/savedump/config.sh, packages/sdb/config.sh, packages/targetcli-fb/config.sh, packages/td-agent/config.sh, packages/zfs/config.sh, template/config.sh
This code cleanup mainly gets rid of the DEFAULT_PACKAGE_VERSION parameter, but also other parameters which aren't being used.
- Rebuild all packages: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-packages/job/pre-push/420/
- ab-pre-push (including upgrade): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4921/
=> TOOL-11267 Remove DEFAULT_PACKAGE_VERSION field from linux-pkg

README.md, buildpkg.sh, lib/common.sh, packages/bpftrace/config.sh, packages/challenge-response/config.sh, packages/cloud-init/config.sh, packages/connstat/config.sh, packages/crash-python/config.sh, packages/crypt-blowfish/config.sh, packages/delphix-kernel/config.sh, packages/delphix-platform/config.sh, packages/drgn/config.sh, packages/gdb-python/config.sh, packages/grub2/config.sh, packages/libkdumpfile/config.sh, packages/make-jpkg/config.sh, packages/makedumpfile/config.sh, packages/nfs-utils/config.sh, packages/performance-diagnostics/config.sh, packages/python-rtslib-fb/config.sh, packages/recovery-environment/config.sh, packages/savedump/config.sh, packages/sdb/config.sh, packages/targetcli-fb/config.sh, packages/td-agent/config.sh, packages/zfs/config.sh, template/config.sh
This is a mostly clean backport of #143, with a trivial conflict because #137 has not been backported to 6.0/stage yet.
=> TOOL-11575 [Backport of TOOL-11267 to 6.0/stage] Remove DEFAULT_PACKAGE_VERSION field from linux-pkg

packages/host-jdks/config.sh
Part 1: Splitting the review for DLPX-74479: host-jdks config.sh
Use the debian directory code from https://github.com/delphix/host-jdks 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/custom/job/build-package/job/custom/64/
=> CP-4971 host-jdks config.sh

package-lists/build/main.pkgs, packages/host-jdks/config.sh, packages/virtualization/config.sh
all host-jdks changes together. host-jdks config.sh, virtualization config.sh and main.pkgs
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5240/console
=> Add dependency on "host-jdks" to "virtualization" package

packages/virtualization/config.sh
Consumers of the virtualization build, expect hostchecker tarballs to reside within the `hostchecker2/tars` sub-directory, but currently they're being placed directly in the `hostchecker2` directory. For example, looking at the S3 output location, I see this:
```
$ aws s3 ls s3://dev-de-images/builds/jenkins-selfservice/devops-gate/master/linux-pkg/master/build-package/virtualization/pre-push/127/hostchecker2/
2021-05-13 19:16:08  171796480 hostchecker_aix_powerpc.tar
2021-05-13 19:16:08  139868160 hostchecker_hpux_ia64.tar
2021-05-13 19:16:08  122931200 hostchecker_linux_x86.tar
2021-05-13 19:16:08  128645120 hostchecker_sunos_sparc.tar
2021-05-13 19:16:09  124794880 hostchecker_sunos_x86.tar
```
As a result, consumers of these files do not work properly; for example, in the …
=> TOOL-11608 Missing hostchecker2 "tars" sub-directory from virtualization build

packages/docker-python-image/config.sh
CP-5111 [Backport of CP-4543 to 6.0.9.0] Write package to pull down Base Docker image of python:2.7.18-slim and save it to disk
=> CP-5111 [Backport of CP-4543 to 6.0.9.0]

package-lists/build/main.pkgs
running git-ab-pre-push with linux-pkg pointing to these changes:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5295/
This does have some other appgate backport changes that requires the linux pkg changes.
In http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/6.0/job/stage/job/combine-packages/job/pre-push/153/console we see:
```
15:41:01  docker-python-image: s3://snapshot-de-images/builds/jenkins-ops/devops-gate/master/linux-pkg/6.0/stage/build-package/docker-python-image/post-push/2
```
=> CP-5111 [Backport of CP-4543 to 6.0.9.0] main.pkgs update follow on

packages/zfs/config.sh
zfs-object-agent is written in rust. We need to install rust devtools on the bootstrap VM before we build the ZFS packages. This change accomplishes that.
Successful build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/zfs/job/pre-push/123/console
Note: We had done this earlier for the delphix appliance.
https://github.com/delphix/appliance-build/pull/544
=> zfs_object_agent build requires cargo, rustc

packages/virtualization/config.sh
Same as the original diff. we need to get the virtualization package to have virtualenv installed.
this isn't the best way to do it because the virtualenv here is a very old version.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5319/
^ this was built with some other appgate backport changes.
=> CP-5081 [Backport of CP-4898 to 6.0.9.0] Write gradle task to download grpcio and generate grpc files

packages/adoptopenjdk/config.sh
This change updates the JDK version to 8u282b08.
Related Reviews
http://reviews.delphix.com/r/66248/
Testing
appliance-build-orchestrator-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5229/
Verification on image from pre-push
```
delphix@ip-10-110-253-227:~$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```
=> Update Java to 8u282b08

packages/crash-python/config.sh, packages/gdb-python/config.sh, packages/savedump/config.sh, packages/sdb/config.sh
git-ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5515/
=> TOOL-11734 linux-pkg should use install_build_deps_from_control_file whenever possible

lib/common.sh, packages/virtualization/config.sh
This changes linux-pkg's recipe to build the virtualization package to use build dependencies list created in TOOL-11756 (pending review: http://reviews.delphix.com/r/70289/)
See testing section in http://reviews.delphix.com/r/70289/
=> TOOL-11757 linux-pkg: use build dependencies list stored in virtualization package repository

default-package-config.sh
Canonical has 2 ways of naming their tags:
* Ubuntu-gcp-5.4.0-1046.49
* Ubuntu-gcp-5.4-5.4.0-1046.49_18.04.1
For a given kernel version and a given distribution, only one naming scheme is being used. When two distributions (such as 20.04 and 18.04) use the same major kernel version, Canonical first applies the patches to one distribution and then creates a base tag. It then backports those changes to the older distribution, and then creates a longer tag name.
For instance with the example above we can see that the base tag exists on the 20.04 remote:
```
$ git ls-remote focal-gcp | grep 1046
7870999272937a8d2e14165409d799c2876771a3 refs/tags/Ubuntu-gcp-5.4.0-1046.49
```
While on 18.04 there is the longer tag name:
```
$ git ls-remote bionic-gcp | grep 1046 …
```
=> TOOL-11815 linux-pkg: kernel sync-with-upstream logic sometimes fails to find expected tags upstream

packages/zfs/config.sh
Backport to 6.0/stage:
```
commit 9148daf3f5ddd4929da3ec43e65db49a91bba5e5 
Author: Manoj Joseph <manoj.joseph@delphix.com>
Date:   Tue May 18 10:29:26 2021 -0700
zfs_object_agent build requires cargo (#169)
```
linux-pkg build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/6.0/job/stage/job/build-package/job/zfs/job/pre-push/57/console PASS
appliance-build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5787/console BUILD SUCCESSFUL
=> zfs_object_agent build requires cargo (#169)

packages/adoptopenjdk/config.sh
Upgrade JDK8 to the latest available version
Manually verified the java version for VM from image created by http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6023/  
```
delphix@ip-10-110-220-219:~$ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
```
No failed tests in orchestrator run.
=> Upgrade jdk version to 8u302b08

packages/delphix-rust/config.sh
```
$ ./buildpkg.sh delphix-rust
...
dpkg-deb: building package 'delphix-rust' in '../delphix-rust_1.0.0-delphix-2021.09.07.17_amd64.deb'.
dpkg-genbuildinfo --build=binary
dpkg-genchanges --build=binary >../delphix-rust_1.0.0-delphix-2021.09.07.17_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
dpkg-source --after-build repo
dpkg-buildpackage: info: binary-only upload (no source included)
Running: cd /home/ubuntu/linux-pkg/packages/delphix-rust/tmp/
Running: mv ./delphix-rust_1.0.0-delphix-2021.09.07.17_amd64.deb artifacts/
PACKAGE delphix-rust: STAGE build COMPLETED in 306 seconds
Running: cd /home/ubuntu/linux-pkg/packages/delphix-rust/tmp
PACKAGE delphix-rust: STAGE store_build_info STARTED
Running: store_build_info
Running: store_git_info
Running: …
```
=> DOSE-501 use newer version of rust to compile agent

README.md, buildpkg.sh, checkupdates.sh, lib/common.sh, push-merge.sh, setup.sh, sync-with-upstream.sh
This is just a convenience feature to make the process simpler for developers to use linux-pkg.
- Manually checked that setup script is run automatically the first time I run buildpkg.sh
- Manually checked that the setup script is run again after a reboot
- Sanity test to make sure build-package job still works: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/cloud-init/job/pre-push/31
=> TOOL-12213 linux-pkg: run setup.sh automatically when needed

lib/common.sh
**Background:**
As part of [TOOL-11833](https://jira.delphix.com/browse/TOOL-11833) I am enabling the child Jenkins jobs to be kicked off from the same branch as the parent job.
**Problem:**
Due to the one to one relationship between the linux-pkg job paths and S3 URLs, enabling this functionality also requires plumbing in the devops-gate branch to the linux-pkg scripts.
**Solution:**
Enable the linux-pkg script to read a `S3_DEVOPS_BRANCH ` environment variable and use that variable.
**Testing:**
~~Ran `linux-pkg-build-package` on my ops dev instance on a development branch, notice how it looks in the correct path but package does not exist: http://collins.d.delphix.com:28565/job/devops-gate/job/t11833-branch-hardcode/job/linux-pkg/job/master/job/build-package/job/virtualization/job/post- …
=> TOOL-12032 Enable linux-pkg to fetch from custom devops-gate branches

packages/containerized-masking/config.sh
This adds a new package for a new flavor of the masking product. Although the output of this job will not be part of the appliance, we are using linux-pkg since linux-pkg provides a number of useful feature for building generic software, like automatically generated Jenkins jobs that will trigger on post-push, the creation of a build environment with the correct build dependencies installed, a simple way to upload output artifacts to S3, etc.
Because this package is not used by the appliance, we do not include it in any of the package lists, so that its build is not triggered by the `build-packages` job or by `git ab-pre-push`.
This new artifact could be built as part of the existing `masking` package by just adding another task to the Gradle invocation in that package's `config.sh`. …
=> JAIL-15 Post-push build for containerized masking

lib/common.sh, packages/grub2/config.sh, packages/linux-kernel-aws/config.delphix.sh, packages/linux-kernel-azure/config.delphix.sh, packages/linux-kernel-gcp/config.delphix.sh, packages/linux-kernel-generic/config.delphix.sh, packages/linux-kernel-oracle/config.delphix.sh, setup.sh
Note: this will only be integrated when transitioning master to Ubuntu 20.04.
The changes are fairly basic:
- Don't install gcc8 anymore because Ubuntu 20.04 is using gcc9, which has all the fixes we needed.
- Update the upstream git url where appropriate
- Change UBUNTU_DISTRIBUTION to "focal", which is used in a few checks.
Those changes have been soaking on the focal branch for a few months
=> TOOL-12355 linux-pkg: changes for Ubuntu 20.04

packages/fluentd-gems/config.sh
As per Prakash's comments in [PR 209](https://github.com/delphix/linux-pkg/pull/209) I have split out the fluentd-gems config changes and cleaned up the copyright.  
"you need to add the packages config.sh file, and add the package to main.pkgs in two independent PRs.. in order to avoid build failures.. the sequence need to be:
add the package's config.sh file
build the package in Jenkins
add the package to main.pkgs
If we don't perform (2) prior to (3), the Jenkins "combine-packages" job will fail to find the package for "fluentd-gems", and result in build failures (e.g. for git-ab-pre-push).. and we can't perform (2), until we've performed (1)..
So, while this is a bit of an awkward dance we need to perform, it's necessary given the current architecture, if we want to avoid impact to …
=> CP-6693 linux-pkg config for fluentd-gems package

lib/common.sh
Clean cherrypick of: https://github.com/delphix/linux-pkg/pull/207
=> TOOL-12536 [Backport of TOOL-12470 to 6.0/stage] Remove Jenkins job references to devops-gate/master in linux-pkg

push-merge.sh
This PR adds the ability to use the FETCH_GIT_TOKEN in this script. We pass it to the ls-remote call so that it can behave correctly on private github repositories. An accompanying change will be required to the devops repository to pass that variable to this script.
=> TOOL-12604 linux-pkg's "push-merge.sh" script does not work for internal github repositories

lib/common.sh, packages/grub2/config.sh, packages/linux-kernel-aws/config.delphix.sh, packages/linux-kernel-azure/config.delphix.sh, packages/linux-kernel-gcp/config.delphix.sh, packages/linux-kernel-generic/config.delphix.sh, packages/linux-kernel-oracle/config.delphix.sh, setup.sh
Note: this will only be integrated when transitioning 6.0/stage to Ubuntu 20.04.
The commit is a clean cherry-pick of https://github.com/delphix/linux-pkg/pull/197 under the covers.
The changes are fairly basic:
* Don't install gcc8 anymore because Ubuntu 20.04 is using gcc9, which has all the fixes we needed.
* Update the upstream git url where appropriate
* Change UBUNTU_DISTRIBUTION to "focal", which is used in a few checks.
Those changes have been soaking on the master branch for a few months
=> TOOL-12417 [Backport of TOOL-12355 to 6.0.13.0] linux-pkg: changes for Ubuntu 20.04

setup.sh
This change introduced the use of an external PPA (deadsnakes) to install Python 3.8 on 6.0.12.0 engines. Now that 6.0/stage is going to be tracking 6.0.13 (which already has Python 3.8 installed), we no longer need this PPA. As such we are reverting the change here
=> Revert "DLPX-78480 6.0/stage build needs python3.8 in order to release vSDK 4.0.0"

package-lists/build/main.pkgs
=> CP-7145 [Backport of CP-5327 to 6.0.13.0] Simplify the fluentd build

packages/misc-debs/config.sh
When integrating CP-5327 (along with app-gate and appliance build changes) into master, app-gate integrations tests failed because of a missing fluentd-gems package.  In order to avoid a similar scenario in stage I will split this backport into two parts.  First, making sure the fluentd-gems package is installed and then updating the td-agent package.  
Then in part two, switch from the delphix built td-agent package to the standard focal td-agent package.  This goes to gether with changes to  the [appliance-build ](url)([delphix/appliance-build#655)](https://github.com/delphix/appliance-build/pull/655) and [app-gate](http://reviews.delphix.com/r/77706/) .
=> CP-7145 [Backport of CP-5327 to 6.0.13.0] Simplify the fluentd build  part 2

lib/common.sh
This change causes our upstream to be set to the LTS kernel for the various cloud platforms. This will cause us to use the 5.4 kernel instead of 5.11; this will work around an issue with the kernel pipe code in 5.11.
Testing:
Kernel build: http://ops.jenkins.delphix.com/job/linux-pkg/job/master/job/build-kernel/job/pre-push/35/console
appliance-build: http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/652/ (upgrade tests are failing due to DLPX-79397)
AWS blackbox: http://selfservice.jenkins.delphix.com/job/blackbox-self-service/8451/consoleFull
GCP blackbox: http://selfservice.jenkins.delphix.com/job/blackbox-self-service/8453/consoleFull
Azure blackbox: http://selfservice.jenkins.delphix.com/job/blackbox-self-service/8501/consoleFull ;  this run has …
=>  CP-7238 consolidate kernel versions to 5.4 

packages/adoptopenjdk/config.sh
Update engine JDK to latest available version 8u332b09
Verified the java version is updated to the latest by cloning an engine from image created from orchestrator run.
ab-pre-push - http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/1702/ 
The failing test is caused by an additional timezone introduced in newer version - addressed in http://reviews.delphix.com/r/79437/
=> CP-7227 Upgrade Engine JDK to version jdk332-b09

push-merge.sh
This is a clean cherry-pick of #216; it's now required on `6.0/stage`, since we're now merging upstream directly to the `6.0/stage` branch of the `delphix/zfs` repository, when previously we were only merging to the `master` branch.
See also: http://reviews.delphix.com/r/80206/
=> TOOL-12604 linux-pkg's "push-merge.sh" script does not work for internal github repositories (#216)

packages/adoptopenjdk/config.sh
###Description
Update engine JDK to latest available version 8u332b09
clean cherry-pick of https://github.com/delphix/linux-pkg/pull/232
###Testing
Verified the java version is updated to the latest by cloning an engine from image created from orchestrator run.
ab-pre-push - http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/1810/
Additional timezone introduced in newer version - addressed in http://reviews.delphix.com/r/81164/
=> CP-8114 [Backport of CP-7227 to 6.0/stage] Upgrade Engine JDK to version jdk332-b09

packages/adoptopenjdk/config.sh
Update engine JDK to latest available version 8u342b07
Verified the java version is updated to the latest by cloning an engine from image created from orchestrator run.
ab-pre-push - http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/2616/
=> DLPX-81830 Upgrade Engine JDK to 8u342-b07

lib/common.sh
This is a git merge of `master` into `6.0/stage`; this is in preparation for development to be done directly on `6.0/stage` instead of `master`.
There were minor conflicts that had to be resolved, see [here](https://github.com/delphix/linux-pkg/pull/238/commits/2f986d37471c49618430e58f2c9207060e421fa7).
There are minor diffs with master after completing this merge:
```
$ git diff origin/master
diff --git a/branch.config b/branch.config
index 506ef72..705e477 100644
--- a/branch.config
+++ b/branch.config
@@ -11,4 +11,4 @@
#
-DEFAULT_GIT_BRANCH="master"
+DEFAULT_GIT_BRANCH="6.0/stage"
diff --git a/packages/zfs/config.sh b/packages/zfs/config.sh
index 3cea75c..f8d40da 100644
--- a/packages/zfs/config.sh
+++ b/packages/zfs/config.sh
@@ -19,6 +19,9 @@ …
```
=> GHM-743 transition more platform repository to pre-gitflow branching model

package-lists/build/main.pkgs, packages/fio/config.sh
Need to build delphix maintained fio which runs on python3. This adds delphix/fio to linux-pkg
Testing:
ab-pre-push: http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/2924/ (upgrade hit a known bug)
Verified this change adds the fio build job to jenkins: http://selfservice.jenkins-sbala.dcol2.delphix.com/job/linux-pkg/job/master/job/build-package/job/fio/
=> DLPX-82230 add delphix/fio to linux-pkg

packages/adoptopenjdk/config.sh
Upgrade engine JDK to latest version available for 6.0.17.0. A newer version of JDK was released to fix a compiler bug after changes were done in master. So, updating the latest version to master as well.
ab-pre-push - http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/3050/
=> DLPX-82803 [Backport of DLPX-81830] Upgrade Engine JDK to 8u345-b01
